# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly

#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get -qq install python-pip
#  - sudo pip install ezodf
#  - sudo pip install lxml

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("OdsIO"); Pkg.test("OdsIO"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("OdsIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("OdsIO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
